In [20]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import  cosine_similarity
from scipy.sparse import  csr_matrix

movies= pd.read_csv('movies.csv')
rating= pd.read_csv('ratings.csv')

In [21]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [22]:
movies.isna().sum()

movieId    0
title      0
genres     0
dtype: int64

In [23]:
movies.describe()

             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

In [24]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   str
 2   genres   9742 non-null   str
dtypes: int64(1), str(2)
memory usage: 626.1 KB

In [25]:
rating

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [26]:
rating.isna().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [27]:
rating.describe()

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [28]:
rating.info()

<class 'pandas.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

# movie_id= int(input("enter  movie id: "))           #movie for which similar movies are needed
top_n= int(input("enter number of recommended movies: "))       #no.of recommandations

#content based filtering
vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix= vectorizer.fit_transform(movies['genres'])

In [30]:
content_similarity = cosine_similarity(tfidf_matrix)

#find similar movies(content-Based)
movie_idx = movies.index[movies['movieId'] == movie_id].tolist()[0]
content_recommandations = list(enumerate(content_similarity[movie_idx]))

content_recommandations

[(0, np.float64(0.13634866508521784)),
 (1, np.float64(0.0)),
 (2, np.float64(0.2909098936874118)),
 (3, np.float64(0.25733057159885575)),
 (4, np.float64(0.509549909506656)),
 (5, np.float64(0.0)),
 (6, np.float64(0.2909098936874118)),
 (7, np.float64(0.0)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0)),
 (10, np.float64(0.25733057159885575)),
 (11, np.float64(1.0)),
 (12, np.float64(0.0)),
 (13, np.float64(0.0)),
 (14, np.float64(0.0)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.509549909506656)),
 (18, np.float64(0.509549909506656)),
 (19, np.float64(0.17948069681326587)),
 (20, np.float64(0.22062678294584237)),
 (21, np.float64(0.42140716439035963)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.0)),
 (25, np.float64(0.0)),
 (26, np.float64(0.0)),
 (27, np.float64(0.0)),
 (28, np.float64(0.0)),
 (29, np.float64(0.0)),
 (30, np.float64(0.0)),
 (31, np.float64(0.0)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.23863177599414026)),
 (35, np.float64(0.2909098936874118)),
 (36, np.float64(0.0)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.26574226280179447)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0)),
 (44, np.float64(0.0)),
 (45, np.float64(0.0)),
 (46, np.float64(0.0)),
 (47, np.float64(0.25733057159885575)),
 (48, np.float64(0.0)),
 (49, np.float64(0.23863177599414026)),
 (50, np.float64(0.0)),
 (51, np.float64(0.0)),
 (52, np.float64(0.25733057159885575)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.0)),
 (56, np.float64(0.27196459695137676)),
 (57, np.float64(0.2909098936874118)),
 (58, np.float64(0.509549909506656)),
 (59, np.float64(0.0)),
 (60, np.float64(0.2909098936874118)),
 (61, np.float64(0.509549909506656)),
 (62, np.float64(0.7143155165923518)),
 (63, np.float64(0.0)),
 (64, np.float64(0.3743315708621761)),
 (65, np.float64(0.0)),
 (66, np.float64(0.0)),
 (67, np.float64(0.3743315708621761)),
 (68, np.float64(0.0)),
 (69, np.float64(0.0)),
 (70, np.float64(0.0)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.3743315708621761)),
 (75, np.float64(0.0)),
 (76, np.float64(0.0)),
 (77, np.float64(0.0)),
 (78, np.float64(0.23863177599414026)),
 (79, np.float64(0.509549909506656)),
 (80, np.float64(0.0)),
 (81, np.float64(0.6179692387068709)),
 (82, np.float64(0.8066247839022408)),
 (83, np.float64(0.25733057159885575)),
 (84, np.float64(0.0)),
 (85, np.float64(0.3743315708621761)),
 (86, np.float64(0.0)),
 (87, np.float64(0.0)),
 (88, np.float64(0.0)),
 (89, np.float64(0.1800959420641523)),
 (90, np.float64(0.509549909506656)),
 (91, np.float64(0.0)),
 (92, np.float64(0.509549909506656)),
 (93, np.float64(0.0)),
 (94, np.float64(0.3743315708621761)),
 (95, np.float64(0.14713255103699407)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.0)),
 (99, np.float64(0.18232966432322792)),
 (100, np.float64(0.0)),
 (101, np.float64(0.0)),
 (102, np.float64(0.0)),
 (103, np.float64(0.2909098936874118)),
 (104, np.float64(0.509549909506656)),
 (105, np.float64(0.0)),
 (106, np.float64(0.2909098936874118)),
 (107, np.float64(0.0)),
 (108, np.float64(0.509549909506656)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.2909098936874118)),
 (112, np.float64(0.0)),
 (113, np.float64(0.509549909506656)),
 (114, np.float64(0.0)),
 (115, np.float64(0.0)),
 (116, np.float64(0.509549909506656)),
 (117, np.float64(0.509549909506656)),
 (118, np.float64(0.17948069681326587)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.0)),
 (124, np.float64(0.0)),
 (125, np.float64(0.7549118349527193)),
 (126, np.float64(0.18232966432322792)),
 (127, np.float64(0.0)),
 (128, np.float64(0.0)),
 (129, np.float64(0.3743315708621761)),
 (130, np.float64(0.21332635424976756)),
 (131, np.float64(0.0)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.0)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.0)),
 (138, np.float64(0.0)),
 (139, np.float64(0.24393861262029828)),
 (140, np.float64(0.0)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.3743315708621761)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.509549909506656)),
 (147, np.float64(0.0)),
 (148, np.float64(0.509549909506656)),
 (149, np.float64(0.8604411018319376)),
 (150, np.float64(0.3743315708621761)),
 (151, np.float64(0.0)),
 (152, np.float64(0.2909098936874118)),
 (153, np.float64(0.0)),
 (154, np.float64(0.8238029431638161)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.2909098936874118)),
 (158, np.float64(0.509549909506656)),
 (159, np.float64(0.460414235400442)),
 (160, np.float64(0.24693633471089704)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (164, np.float64(0.3743315708621761)),
 (165, np.float64(0.25733057159885575)),
 (166, np.float64(0.4969809174030388)),
 (167, np.float64(0.0)),
 (168, np.float64(0.0)),
 (169, np.float64(0.0)),
 (170, np.float64(0.0)),
 (171, np.float64(0.509549909506656)),
 (172, np.float64(0.0)),
 (173, np.float64(0.3743315708621761)),
 (174, np.float64(0.0)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.0)),
 (180, np.float64(0.16288135792075684)),
 (181, np.float64(0.0)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.509549909506656)),
 (185, np.float64(0.0)),
 (186, np.float64(0.3743315708621761)),
 (187, np.float64(0.0)),
 (188, np.float64(0.8604411018319376)),
 (189, np.float64(0.0)),
 (190, np.float64(0.509549909506656)),
 (191, np.float64(0.25733057159885575)),
 (192, np.float64(0.0)),
 (193, np.float64(0.0)),
 (194, np.float64(0.509549909506656)),
 (195, np.float64(0.0)),
 (196, np.float64(0.0)),
 (197, np.float64(0.27526214954255557)),
 (198, np.float64(0.25733057159885575)),
 (199, np.float64(0.0)),
 (200, np.float64(0.509549909506656)),
 (201, np.float64(0.3743315708621761)),
 (202, np.float64(0.2292323629186261)),
 (203, np.float64(0.2909098936874118)),
 (204, np.float64(0.0)),
 (205, np.float64(0.15839139790740203)),
 (206, np.float64(0.0)),
 (207, np.float64(0.0)),
 (208, np.float64(0.0)),
 (209, np.float64(0.18224409767394192)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (212, np.float64(0.509549909506656)),
 (213, np.float64(0.0)),
 (214, np.float64(0.23863177599414026)),
 (215, np.float64(0.0)),
 (216, np.float64(0.2909098936874118)),
 (217, np.float64(0.7549118349527193)),
 (218, np.float64(0.0)),
 (219, np.float64(0.509549909506656)),
 (220, np.float64(0.19691679790529165)),
 (221, np.float64(0.0)),
 (222, np.float64(0.14521737631851742)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.0)),
 (229, np.float64(0.0)),
 (230, np.float64(0.509549909506656)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.3743315708621761)),
 (235, np.float64(0.4738980498148572)),
 (236, np.float64(0.509549909506656)),
 (237, np.float64(0.509549909506656)),
 (238, np.float64(0.2909098936874118)),
 (239, np.float64(0.0)),
 (240, np.float64(0.509549909506656)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.25733057159885575)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (246, np.float64(0.0)),
 (247, np.float64(0.7549118349527193)),
 (248, np.float64(0.2909098936874118)),
 (249, np.float64(0.0)),
 (250, np.float64(0.2909098936874118)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.0)),
 (254, np.float64(0.0)),
 (255, np.float64(0.2909098936874118)),
 (256, np.float64(0.2909098936874118)),
 (257, np.float64(0.2048552894206736)),
 (258, np.float64(0.0)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.0)),
 (262, np.float64(0.0)),
 (263, np.float64(0.0)),
 (264, np.float64(0.3743315708621761)),
 (265, np.float64(0.509549909506656)),
 (266, np.float64(0.0)),
 (267, np.float64(0.0)),
 (268, np.float64(0.3743315708621761)),
 (269, np.float64(0.509549909506656)),
 (270, np.float64(0.6719798692114795)),
 (271, np.float64(0.509549909506656)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.0)),
 (276, np.float64(0.2253914300375626)),
 (277, np.float64(0.0)),
 (278, np.float64(0.26574226280179447)),
 (279, np.float64(0.0)),
 (280, np.float64(0.0)),
 (281, np.float64(0.3743315708621761)),
 (282, np.float64(0.3743315708621761)),
 (283, np.float64(0.509549909506656)),
 (284, np.float64(0.0)),
 (285, np.float64(0.1740695678850359)),
 (286, np.float64(0.6719798692114795)),
 (287, np.float64(0.0)),
 (288, np.float64(0.5401819212358606)),
 (289, np.float64(0.0)),
 (290, np.float64(0.4969809174030388)),
 (291, np.float64(0.509549909506656)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.0)),
 (296, np.float64(0.0)),
 (297, np.float64(0.2909098936874118)),
 (298, np.float64(0.0)),
 (299, np.float64(0.0)),
 (300, np.float64(0.509549909506656)),
 (301, np.float64(0.0)),
 (302, np.float64(0.509549909506656)),
 (303, np.float64(0.3743315708621761)),
 (304, np.float64(0.0)),
 (305, np.float64(0.0)),
 (306, np.float64(0.509549909506656)),
 (307, np.float64(0.0)),
 (308, np.float64(0.0)),
 (309, np.float64(0.25733057159885575)),
 (310, np.float64(0.3743315708621761)),
 (311, np.float64(0.0)),
 (312, np.float64(0.0)),
 (313, np.float64(0.18224409767394192)),
 (314, np.float64(0.1734897739703282)),
 (315, np.float64(0.2909098936874118)),
 (316, np.float64(0.0)),
 (317, np.float64(0.25733057159885575)),
 (318, np.float64(0.3006171245092258)),
 (319, np.float64(0.25733057159885575)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0)),
 (323, np.float64(0.0)),
 (324, np.float64(0.4744704646047199)),
 (325, np.float64(0.17333852238258154)),
 (326, np.float64(0.16001113066315586)),
 (327, np.float64(0.0)),
 (328, np.float64(0.3006171245092258)),
 (329, np.float64(0.3743315708621761)),
 (330, np.float64(0.25733057159885575)),
 (331, np.float64(0.0)),
 (332, np.float64(0.23863177599414026)),
 (333, np.float64(0.0)),
 (334, np.float64(0.0)),
 (335, np.float64(0.2909098936874118)),
 (336, np.float64(0.0)),
 (337, np.float64(0.1680710707347735)),
 (338, np.float64(0.0)),
 (339, np.float64(0.5271806337975027)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0)),
 (342, np.float64(0.0)),
 (343, np.float64(0.0)),
 (344, np.float64(0.3006171245092258)),
 (345, np.float64(0.0)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.0)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.6719798692114795)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.18224409767394192)),
 (356, np.float64(0.0)),
 (357, np.float64(0.509549909506656)),
 (358, np.float64(0.509549909506656)),
 (359, np.float64(0.30323300803994946)),
 (360, np.float64(0.0)),
 (361, np.float64(0.2909098936874118)),
 (362, np.float64(0.0)),
 (363, np.float64(0.509549909506656)),
 (364, np.float64(0.18980424518653233)),
 (365, np.float64(0.0)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.4511737734901365)),
 (371, np.float64(0.0)),
 (372, np.float64(0.0)),
 (373, np.float64(0.509549909506656)),
 (374, np.float64(0.3743315708621761)),
 (375, np.float64(0.0)),
 (376, np.float64(0.16001113066315586)),
 (377, np.float64(0.509549909506656)),
 (378, np.float64(0.0)),
 (379, np.float64(0.19691679790529165)),
 (380, np.float64(0.0)),
 (381, np.float64(0.509549909506656)),
 (382, np.float64(0.26397633390798475)),
 (383, np.float64(0.2909098936874118)),
 (384, np.float64(0.509549909506656)),
 (385, np.float64(0.0)),
 (386, np.float64(0.2909098936874118)),
 (387, np.float64(0.509549909506656)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0)),
 (390, np.float64(0.509549909506656)),
 (391, np.float64(0.3743315708621761)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.2909098936874118)),
 (395, np.float64(0.0)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0)),
 (401, np.float64(0.509549909506656)),
 (402, np.float64(0.0)),
 (403, np.float64(0.0)),
 (404, np.float64(0.18509582434175245)),
 (405, np.float64(0.509549909506656)),
 (406, np.float64(0.2909098936874118)),
 (407, np.float64(0.0)),
 (408, np.float64(0.509549909506656)),
 (409, np.float64(0.509549909506656)),
 (410, np.float64(0.3743315708621761)),
 (411, np.float64(0.21332635424976756)),
 (412, np.float64(0.0)),
 (413, np.float64(0.0)),
 (414, np.float64(0.3743315708621761)),
 (415, np.float64(0.0)),
 (416, np.float64(0.24393861262029828)),
 (417, np.float64(0.0)),
 (418, np.float64(0.0)),
 (419, np.float64(0.0)),
 (420, np.float64(0.0)),
 (421, np.float64(0.0)),
 (422, np.float64(0.17418314333019347)),
 (423, np.float64(0.509549909506656)),
 (424, np.float64(0.18346131798202114)),
 (425, np.float64(0.0)),
 (426, np.float64(0.509549909506656)),
 (427, np.float64(0.0)),
 (428, np.float64(0.0)),
 (429, np.float64(0.23138653903016804)),
 (430, np.float64(0.0)),
 (431, np.float64(0.0)),
 (432, np.float64(0.0)),
 (433, np.float64(0.21259579560159747)),
 (434, np.float64(0.2909098936874118)),
 (435, np.float64(0.2909098936874118)),
 (436, np.float64(0.3743315708621761)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0)),
 (440, np.float64(0.509549909506656)),
 (441, np.float64(0.0)),
 (442, np.float64(0.0)),
 (443, np.float64(0.0)),
 (444, np.float64(0.0)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.4969809174030388)),
 (448, np.float64(0.19373665042101032)),
 (449, np.float64(0.509549909506656)),
 (450, np.float64(0.0)),
 (451, np.float64(0.3743315708621761)),
 (452, np.float64(0.0)),
 (453, np.float64(0.509549909506656)),
 (454, np.float64(0.0)),
 (455, np.float64(0.509549909506656)),
 (456, np.float64(0.0)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0)),
 (462, np.float64(0.3743315708621761)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.7780778411045917)),
 (466, np.float64(0.0)),
 (467, np.float64(0.0)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.25733057159885575)),
 (473, np.float64(0.0)),
 (474, np.float64(0.0)),
 (475, np.float64(0.25733057159885575)),
 (476, np.float64(0.230385905368797)),
 (477, np.float64(0.0)),
 (478, np.float64(0.12073028108873973)),
 (479, np.float64(0.0)),
 (480, np.float64(0.0)),
 (481, np.float64(0.0)),
 (482, np.float64(0.2909098936874118)),
 (483, np.float64(0.0)),
 (484, np.float64(0.1877229986927208)),
 (485, np.float64(0.0)),
 (486, np.float64(0.0)),
 (487, np.float64(0.0)),
 (488, np.float64(0.0)),
 (489, np.float64(0.3743315708621761)),
 (490, np.float64(0.0)),
 (491, np.float64(0.509549909506656)),
 (492, np.float64(0.3743315708621761)),
 (493, np.float64(0.3743315708621761)),
 (494, np.float64(0.3743315708621761)),
 (495, np.float64(0.0)),
 (496, np.float64(0.3743315708621761)),
 (497, np.float64(0.23863177599414026)),
 (498, np.float64(0.0)),
 (499, np.float64(0.0)),
 (500, np.float64(0.0)),
 (501, np.float64(0.0)),
 (502, np.float64(0.3743315708621761)),
 (503, np.float64(0.509549909506656)),
 (504, np.float64(0.23863177599414026)),
 (505, np.float64(0.16982510515034088)),
 (506, np.float64(0.12853514002666572)),
 (507, np.float64(0.0)),
 (508, np.float64(0.0)),
 (509, np.float64(0.0)),
 (510, np.float64(0.5420339540952114)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.0)),
 (514, np.float64(0.2909098936874118)),
 (515, np.float64(0.0)),
 (516, np.float64(0.2196130800324843)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.5878338025199977)),
 (520, np.float64(0.2048552894206736)),
 (521, np.float64(0.0)),
 (522, np.float64(0.3569507124414996)),
 (523, np.float64(0.45010401851130116)),
 (524, np.float64(0.509549909506656)),
 (525, np.float64(0.0)),
 (526, np.float64(0.3743315708621761)),
 (527, np.float64(0.0)),
 (528, np.float64(0.3743315708621761)),
 (529, np.float64(0.2909098936874118)),
 (530, np.float64(0.509549909506656)),
 (531, np.float64(0.509549909506656)),
 (532, np.float64(0.0)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.0)),
 (536, np.float64(0.509549909506656)),
 (537, np.float64(0.509549909506656)),
 (538, np.float64(0.3743315708621761)),
 (539, np.float64(0.0)),
 (540, np.float64(0.509549909506656)),
 (541, np.float64(0.0)),
 (542, np.float64(0.3743315708621761)),
 (543, np.float64(0.0)),
 (544, np.float64(0.0)),
 (545, np.float64(0.0)),
 (546, np.float64(0.0)),
 (547, np.float64(0.3743315708621761)),
 (548, np.float64(0.0)),
 (549, np.float64(0.0)),
 (550, np.float64(0.509549909506656)),
 (551, np.float64(0.0)),
 (552, np.float64(0.0)),
 (553, np.float64(0.509549909506656)),
 (554, np.float64(0.1989713758344084)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.0)),
 (558, np.float64(0.19691679790529165)),
 (559, np.float64(0.11491435694472228)),
 (560, np.float64(0.16870461712166526)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.1610921000243322)),
 (566, np.float64(0.2909098936874118)),
 (567, np.float64(0.0)),
 (568, np.float64(0.0)),
 (569, np.float64(0.0)),
 (570, np.float64(0.0)),
 (571, np.float64(0.0)),
 (572, np.float64(0.509549909506656)),
 (573, np.float64(0.0)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.0)),
 (577, np.float64(0.2909098936874118)),
 (578, np.float64(0.12853514002666572)),
 (579, np.float64(0.509549909506656)),
 (580, np.float64(0.0)),
 (581, np.float64(0.0)),
 (582, np.float64(0.0)),
 (583, np.float64(0.16150683574179514)),
 (584, np.float64(0.509549909506656)),
 (585, np.float64(0.19058067825753838)),
 (586, np.float64(0.0)),
 (587, np.float64(0.49018221140363744)),
 (588, np.float64(0.509549909506656)),
 (589, np.float64(0.0)),
 (590, np.float64(0.509549909506656)),
 (591, np.float64(0.0)),
 (592, np.float64(0.0)),
 (593, np.float64(0.8604411018319376)),
 (594, np.float64(0.0)),
 (595, np.float64(0.0)),
 (596, np.float64(0.0)),
 (597, np.float64(0.6719798692114795)),
 (598, np.float64(0.509549909506656)),
 (599, np.float64(0.1770671984498489)),
 (600, np.float64(0.509549909506656)),
 (601, np.float64(0.0)),
 (602, np.float64(0.21332635424976756)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.0)),
 (607, np.float64(0.27196459695137676)),
 (608, np.float64(0.0)),
 (609, np.float64(0.3743315708621761)),
 (610, np.float64(0.0)),
 (611, np.float64(0.0)),
 (612, np.float64(0.5612891016532566)),
 (613, np.float64(0.24393861262029828)),
 (614, np.float64(0.0)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.0)),
 (618, np.float64(0.0)),
 (619, np.float64(0.30323300803994946)),
 (620, np.float64(0.509549909506656)),
 (621, np.float64(0.0)),
 (622, np.float64(0.1469605289273678)),
 (623, np.float64(0.0)),
 (624, np.float64(0.0)),
 (625, np.float64(0.0)),
 (626, np.float64(0.0)),
 (627, np.float64(0.8238029431638161)),
 (628, np.float64(0.0)),
 (629, np.float64(0.23863177599414026)),
 (630, np.float64(0.0)),
 (631, np.float64(0.25733057159885575)),
 (632, np.float64(0.2909098936874118)),
 (633, np.float64(0.0)),
 (634, np.float64(0.0)),
 (635, np.float64(0.0)),
 (636, np.float64(0.0)),
 (637, np.float64(0.18224409767394192)),
 (638, np.float64(0.509549909506656)),
 (639, np.float64(0.509549909506656)),
 (640, np.float64(0.0)),
 (641, np.float64(0.0)),

In [31]:
content_recommandations = sorted(content_recommandations,key=lambda x:x[1],reverse=True)[1:top_n+1]
content_recommendations = [movies.iloc[i[0]]['title'] for i in content_recommandations]

# 2. Convert that list into a DataFrame
df_recommendations = pd.DataFrame(contend_recommendations, columns=['Movie Title'])
print(df_recommendations)

# print(contend_recommendations)

                             Movie Title
0                 American Psycho (2000)
1  Book of Shadows: Blair Witch 2 (2000)
2                       From Hell (2001)
3                        Identity (2003)
4                    House of Wax (1953)

# user based recommendatios

In [32]:
rating

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [33]:
#Preprocess the data
# create a user-movie interation matrics
user_movie_matrix= rating.pivot(index='userId', columns='movieId', values='rating').fillna(0)
user_movie_matrix

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
user_movie_sparse = csr_matrix(user_movie_matrix.values)
user_movie_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 100836 stored elements and shape (610, 9724)>

In [35]:
user_id= int(input('enter user id: ')) # user for whom recommendations are needed 
top_n= int(input('enter number of recommendation movies: '))   #Number of recommendations

user_similarity= cosine_similarity(user_movie_sparse)
#find similar users
user_idx= user_id-1 #conver to 0 based index
similar_users= list(enumerate(user_similarity[user_idx]))
similar_users= sorted(similar_users, key=lambda x: x[1],reverse=True)[1:top_n+1] 
#[1:top_n+1]: Slices the sorted list.It starts at index 1 because index 0 is the target user compared to themselves (similarity score of 1.0).


# get recommended movies from users (user-Based)
user_recommendations=[]
for user in similar_users:
    similar_user_id = user[0] +1 #Convert back to 1-based userid
    movie_rated_by_similar_user = rating[rating['userId'] == similar_user_id]['movieId']
    user_recommendations.extend(movie_rated_by_similar_user)

#Remove duplicates and movies  already rated by the user
#when recommending from previous user rating, we Remove duplicates from new recommending user which the movie already rated by the user
user_rated_movies = rating[rating['userId'] == user_id]['movieId']
user_recommendations = list(set(user_recommendations) - set(user_rated_movies))

#Convert movie IDs to title
user_recommendations = [movies[movies['movieId']== movieId]['title'].values[0] for movieId in user_recommendations][:top_n]
print(user_recommendations)

enter user id:  31
enter number of recommendation movies:  3

['Grumpier Old Men (1995)', 'Robin Hood: Prince of Thieves (1991)', 'Heat (1995)']

# Hybrid recommendations

In [37]:
movie_id=int(input('enter movie id: '))
user_id= int(input('enter user id: '))
top_n= int(input('enter number of recommendation movies: '))

vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix= vectorizer.fit_transform(movies['genres'])
content_similarity = cosine_similarity(tfidf_matrix)

#find similar movies(content-Based)
movie_idx = movies.index[movies['movieId'] == movie_id].tolist()[0]
content_recommandations = list(enumerate(content_similarity[movie_idx]))
content_recommandations = sorted(content_recommandations,key=lambda x:x[1],reverse=True)[1:top_n+1]
content_recommendations = [movies.iloc[i[0]]['title'] for i in content_recommandations]

user_similarity= cosine_similarity(user_movie_sparse)

#find similar users
user_idx= user_id-1 #convert to 0 based index
similar_users= list(enumerate(user_similarity[user_idx]))
similar_users= sorted(similar_users, key=lambda x: x[1],reverse=True)[1:top_n+1]

user_rated_movies = rating[rating['userId'] == user_id]['movieId']
user_recommendations = list(set(user_recommendations) - set(user_rated_movies))
user_recommendations = [movies[movies['movieId']== movie_id]['title'].values[0] for movieId in user_recommendations][:top_n]

# Combine Content-Based and User-Based Recommendations
hybrid_recommendations = list(set(content_recommendations + user_recommendations))[:top_n]

# Display recommendations
print(f"Hybrid Recommendations for User {user_id}: {hybrid_recommendations}")

enter movie id:  22
enter user id:  21
enter number of recommendation movies:  5

Hybrid Recommendations for User 21: ['American Psycho (2000)', 'From Hell (2001)', 'Book of Shadows: Blair Witch 2 (2000)', 'Identity (2003)', 'Copycat (1995)']